#!/bin/bash
# REV00: Wed Sep 12 18:35:04 WIB 2018
# START: Wed Sep 12 18:35:04 WIB 2018

# R: list of all users logged in

# Copyright (C) 2018 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.




exit 0
