#!/bin/bash
# Copyright (C) 2017-2019 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# REV02: Thu Jan 17 11:13:06 WIB 2019
# REV01: Thu Mar 30 17:29:35 WIB 2017
# START: Wed Mar 29 17:28:20 WIB 2017
# ===============================================
# cut     remove sections from each line of files
# cut -c  select only these characters
# sha1sum compute and check SHA1 message digest
# tr      translate or delete characters

isADigit() {
   [[ $VARIABLE =~ $REGEX ]] || {
      TEXT1="VARIABLE $VARIABLE is not a digit."
      return
   }
   [[ ${#VARIABLE}} =~ $TEN ]] && {
      TEXT1="VARIABLE $VARIABLE has 10 digits."
      return
   }
   TEXT1="VARIABLE $VARIABLE has no 10 digits."
}

ONE='1'
TEN='10'
REGEX='^[0-9]+$'
VARIABLE='1234567892'
HASH=`echo "$VARIABLE" | sha1sum`
echo        "$HASH"
isADigit
TEXT2=`echo "$HASH"  | cut -c1-3`
TEXT3=`echo "$TEXT2" | tr '[a-z]' '[A-Z]'`
echo "$TEXT1"
echo "$TEXT2"
echo "$TEXT3"
exit 0

