#!/bin/bash
# REV00: Thu Jan 17 11:21:44 WIB 2019
# START: Xxx Xxx XX XX:XX:XX XXX XXXX
# 
# Copyright (C) 2018-2019 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

VAR="talas"
echo "$VAR"
KALIMAT="Keladi tidak sama dengan $VAR"
echo "$KALIMAT"
echo "$KALIMAT" | gawk '$5 ~ /s$/ {print $1}'

